-- 1.A
CREATE TABLE S6_LRS(
    GEOM SDO_GEOMETRY
);

-- 1.B
INSERT INTO S6_LRS 
SELECT SAR.GEOM FROM STREETS_AND_RAILROADS SAR, MAJOR_CITIES MC
WHERE SDO_RELATE(SAR.GEOM, SDO_GEOM.SDO_BUFFER(MC.GEOM, 10, 1, 'unit=km'), 'MASK=ANYINTERACT') = 'TRUE'
AND MC.CITY_NAME = 'Koszalin';

-- 1.C
SELECT SDO_GEOM.SDO_LENGTH(GEOM, 1, 'unit=km') DISTANCE, ST_LINESTRING(GEOM).ST_NUMPOINTS() ST_NUMPOINTS
FROM S6_LRS;

-- 1.D
UPDATE S6_LRS
SET GEOM = (SELECT SDO_LRS.CONVERT_TO_LRS_GEOM(GEOM, 0, 276.681315399186) FROM S6_LRS) 
WHERE 1=1;

-- 1.E
INSERT INTO USER_SDO_GEOM_METADATA
VALUES ('S6_LRS','GEOM',
MDSYS.SDO_DIM_ARRAY(
 MDSYS.SDO_DIM_ELEMENT('X', 12.603676, 26.369824, 1),
 MDSYS.SDO_DIM_ELEMENT('Y', 45.8464, 58.0213, 1),
 MDSYS.SDO_DIM_ELEMENT('M', 0, 300, 1) ),
 8307);
 
-- 1.F
CREATE INDEX lrs_routes_idx ON S6_LRS(GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

-- 2.A
SELECT SDO_LRS.VALID_MEASURE(GEOM, 500) VALID_500
FROM S6_LRS;

-- 2.B
SELECT SDO_LRS.GEOM_SEGMENT_END_PT(GEOM) END_PT
FROM S6_LRS;

-- 2.C
SELECT SDO_LRS.LOCATE_PT(GEOM, 150, 0) KM150 
FROM S6_LRS;

-- 2.D
SELECT SDO_LRS.CLIP_GEOM_SEGMENT(GEOM, 120, 160) CLIPPED
FROM S6_LRS;

-- 2.E
SELECT SDO_LRS.GET_NEXT_SHAPE_PT(S6.GEOM, SDO_LRS.PROJECT_PT(S6.GEOM, C.GEOM)) WJAZD_NA_S6
FROM S6_LRS S6, MAJOR_CITIES C
WHERE C.CITY_NAME = 'Slupsk';

-- 2.F
SELECT SDO_GEOM.SDO_LENGTH(SDO_LRS.OFFSET_GEOM_SEGMENT(S6.GEOM, M.DIMINFO, 50, 200, 50, 'unit=m'), 1, 'unit=km') KOSZT
FROM S6_LRS S6, USER_SDO_GEOM_METADATA M
WHERE M.TABLE_NAME = 'S6_LRS' AND M.COLUMN_NAME = 'GEOM';





