-- 1.A
CREATE TABLE FIGURY (
id NUMBER(1) PRIMARY KEY,
ksztalt MDSYS.SDO_GEOMETRY
);

-- 1.B
DELETE FROM FIGURY WHERE 1=1;
INSERT INTO FIGURY VALUES (
    1,
    MDSYS.SDO_GEOMETRY(2003, NULL, NULL, 
    MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 4),
    MDSYS.SDO_ORDINATE_ARRAY(5,7, 7,5, 5,3)
));
INSERT INTO FIGURY VALUES (
    2,
    MDSYS.SDO_GEOMETRY(2003, NULL, NULL, 
    MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 3),
    MDSYS.SDO_ORDINATE_ARRAY(1,1, 5,5)
));
INSERT INTO FIGURY VALUES (
    3,
    MDSYS.SDO_GEOMETRY(2002, NULL, NULL, 
    MDSYS.SDO_ELEM_INFO_ARRAY(1,4,2, 1,2,1, 5,2,2),
    MDSYS.SDO_ORDINATE_ARRAY(3,2, 6,2, 7,3, 8,2, 7,1)
));

-- 1.C
INSERT INTO FIGURY VALUES (
    4,
    MDSYS.SDO_GEOMETRY(2003, NULL, NULL, 
    MDSYS.SDO_ELEM_INFO_ARRAY(1, 1003, 4),
    MDSYS.SDO_ORDINATE_ARRAY(5,5, 5,6, 5,7)
));

-- 1.D
SELECT SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(ksztalt, 0.1) as VALID FROM FIGURY;

-- 1.E
DELETE FROM FIGURY WHERE SDO_GEOM.VALIDATE_GEOMETRY_WITH_CONTEXT(ksztalt, 0.1) <> 'TRUE';

-- 1.F
commit;