-- 1.A - Przekopiowanie kodu
-- 1.B - Przekopiowanie kodu
-- 1.C
CREATE TABLE MYST_MAJOR_CITIES(
    FIPS_CNTRY VARCHAR2(2),
    CITY_NAME VARCHAR2(40),
    STGEOM ST_POINT
);

-- 1.D
INSERT INTO MYST_MAJOR_CITIES
SELECT fips_cntry, city_name, treat(ST_POINT.FROM_SDO_GEOM(geom) as ST_POINT) STGEOM
FROM ZTPD.MAJOR_CITIES;

SELECT * FROM MYST_MAJOR_CITIES;
-- 2.A
INSERT INTO MYST_MAJOR_CITIES
VALUES('PL', 'Szczyrek', NEW ST_POINT (19.036107, 49.718655, 4326));

DELETE FROM MYST_MAJOR_CITIES WHERE city_name='Szczyrek';
-- 3.A
CREATE TABLE MYST_COUNTRY_BOUNDARIES(
    FIPS_CNTRY VARCHAR2(2),
    CNTRY_NAME VARCHAR2(40),
    STGEOM ST_MULTIPOLYGON
);

-- 3.B
INSERT INTO MYST_COUNTRY_BOUNDARIES
SELECT fips_cntry, cntry_name, (ST_MULTIPOLYGON(GEOM)) STGEOM
FROM COUNTRY_BOUNDARIES;

-- 3.C
SELECT
    B.STGEOM.ST_GEOMETRYTYPE() TYP_OBIEKTU,
    COUNT(*) ILE
FROM MYST_COUNTRY_BOUNDARIES B
GROUP BY B.STGEOM.ST_GEOMETRYTYPE();

-- 3.D
SELECT B.STGEOM.ST_ISSIMPLE()
FROM MYST_COUNTRY_BOUNDARIES B;

-- 4.A
SELECT cntry_name, count(*)
FROM MYST_MAJOR_CITIES MMC
LEFT JOIN MYST_COUNTRY_BOUNDARIES MCB ON MMC.STGEOM.ST_WITHIN(MCB.STGEOM) = 1
GROUP BY cntry_name;

-- 4.B
SELECT MCB1.CNTRY_NAME A_NAME, MCB2.CNTRY_NAME B_NAME
FROM MYST_COUNTRY_BOUNDARIES MCB1
LEFT JOIN MYST_COUNTRY_BOUNDARIES MCB2 ON MCB1.STGEOM.ST_TOUCHES(MCB2.STGEOM) = 1
WHERE MCB2.CNTRY_NAME = 'Czech Republic';

-- 4.C
SELECT DISTINCT cntry_name, r.name name
FROM MYST_COUNTRY_BOUNDARIES MCB
LEFT JOIN ZTPD.RIVERS R ON MCB.STGEOM.ST_INTERSECTS(ST_LINESTRING(R.GEOM)) = 1
WHERE MCB.CNTRY_NAME = 'Czech Republic';

-- 4.D
SELECT TREAT (A.STGEOM.ST_UNION(B.STGEOM) as ST_POLYGON).ST_AREA() CZECHOSLOWACJA
FROM MYST_COUNTRY_BOUNDARIES A, MYST_COUNTRY_BOUNDARIES B
WHERE A.CNTRY_NAME = 'Czech Republic' AND B.CNTRY_NAME = 'Slovakia';

-- 4.E
SELECT B.STGEOM.ST_DIFFERENCE(ST_GEOMETRY(W.GEOM)) OBIEKT, B.STGEOM.ST_DIFFERENCE(ST_GEOMETRY(W.GEOM)).ST_GEOMETRYTYPE() as WEGRY_BEZ
FROM MYST_COUNTRY_BOUNDARIES B, WATER_BODIES W
WHERE B.CNTRY_NAME = 'Hungary'
AND W.NAME = 'Balaton';

-- 5.A
SELECT B.CNTRY_NAME, C.CITY_NAME
FROM MYST_COUNTRY_BOUNDARIES B, MYST_MAJOR_CITIES C
WHERE SDO_WITHIN_DISTANCE(C.STGEOM, B.STGEOM, 'distance=100 unit=km') = 'TRUE'
AND B.CNTRY_NAME = 'Poland'
AND C.STGEOM.ST_WITHIN(B.STGEOM) != 1;

-- 5.B
INSERT INTO USER_SDO_GEOM_METADATA
SELECT 'MYST_MAJOR_CITIES', 'STGEOM', T.DIMINFO, T.SRID
FROM ALL_SDO_GEOM_METADATA T
WHERE T.TABLE_NAME = 'MAJOR_CITIES';

-- 5.C
CREATE INDEX MYST_MAJOR_CITIES_IDX ON MYST_MAJOR_CITIES(STGEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

-- 5.D
EXPLAIN PLAN FOR
SELECT B.CNTRY_NAME, C.CITY_NAME
FROM MYST_COUNTRY_BOUNDARIES B, MYST_MAJOR_CITIES C
WHERE SDO_WITHIN_DISTANCE(C.STGEOM, B.STGEOM, 'distance=100 unit=km') = 'TRUE'
AND B.CNTRY_NAME = 'Poland'

AND C.STGEOM.ST_WITHIN(B.STGEOM) != 1;
